
# Habilitar el endpoint de Prometheus para las métricas
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Exponer el endpoint de Prometheus
management.endpoint.prometheus.enabled=true